# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Teddy's Knowledge
tagline:             '.NET, Open Source, Cassandra, RabbitMQ, ELK, Architecture, etc'
description:         "Teddy Ma, full-stack software developer/architect in internet & online education industry for 15 years @ Shanghai, China"
#url:                 http://teddyma.cn
baseurl:             ''
gems:				 ["jekyll-paginate", "jekyll-picture-tag"]
paginate:            5
markdown:            kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# About/contact
author:
  name:              Teddy Ma
  url:               https://twitter.com/teddyma_cn
  email:             shijie.ma@gmail.com

# Custom vars
version:             1.0.0

# Image
picture:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
    default:
      attr:
        itemprop: image
      source_full:
        width: 720
      source_lrg:
        media: "(min-width: 40em)"
        width: 720
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 250
    half:
      attr:
        itemprop: image
      source_full:
        width: 720
      source_lrg:
        media: "(min-width: 40em)"
        width: 450
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 150
