# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Teddy's Knowledge
tagline:             '.NET, Open Source, Cassandra, RabbitMQ, ELK, Architecture, etc'
description:         "Teddy Ma, full-stack software developer/architect in internet & online education industry for 15 years @ Shanghai, China"
url:                 http://teddyma.cn
baseurl:             ''
gems:				 ["jekyll-paginate"]
paginate:            5

# About/contact
author:
  name:              Teddy Ma
  url:               https://twitter.com/teddyma_cn
  email:             shijie.ma@gmail.com

# Custom vars
version:             1.0.0
